import { generatedCatalogs } from "./i18n.generated";

export type Locale = "en" | "ar" | "es" | "pt" | "fr" | "de" | "it" | "tr" | "ja" | "ko" | "zh" | "hi" | "ru" | "id";

export const supportedLocales: Array<{ code: Locale; label: string; dir: "ltr" | "rtl" }> = [
  { code: "en", label: "English", dir: "ltr" },
  { code: "ar", label: "العربية", dir: "rtl" },
  { code: "es", label: "Español", dir: "ltr" },
  { code: "pt", label: "Português", dir: "ltr" },
  { code: "fr", label: "Français", dir: "ltr" },
  { code: "de", label: "Deutsch", dir: "ltr" },
  { code: "it", label: "Italiano", dir: "ltr" },
  { code: "tr", label: "Türkçe", dir: "ltr" },
  { code: "ja", label: "日本語", dir: "ltr" },
  { code: "ko", label: "한국어", dir: "ltr" },
  { code: "zh", label: "简体中文", dir: "ltr" },
  { code: "hi", label: "हिन्दी", dir: "ltr" },
  { code: "ru", label: "Русский", dir: "ltr" },
  { code: "id", label: "Bahasa Indonesia", dir: "ltr" },
];

export type TranslationKey = keyof typeof generatedCatalogs.en;
export const dictionary = generatedCatalogs;
let activeLocale: Locale = "en";

const supplementalTranslations: Partial<Record<Locale, Record<string, string>>> = {
  ar: {
    "30 minutes": "30 دقيقة", "6 days": "6 أيام", "2 tasks": "مهمتان", min: "دقيقة", days: "أيام", "min studied": "دقيقة دراسة", "weak topics": "مواضيع ضعيفة",
    Understand: "افهم", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "حوّل المحاضرات والملاحظات والصور والصوت إلى مواضيع وشروحات وملخصات مرتبطة بالمصادر.", Practice: "مارس", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "احصل على أسئلة تناسب المادة، من التعريفات والحسابات إلى التفكير المفتوح.", "Know what is next": "اعرف خطوتك التالية", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "يوازن مدير الدراسة بين الامتحانات ونقاط الضعف والثقة والوقت لاختيار الجلسة التالية المفيدة.", "Separate subject spaces": "مساحات منفصلة لكل مادة", "Save what matters": "احفظ ما يهمك", "Sessions that resume": "جلسات قابلة للاستئناف", "Private by design": "الخصوصية أساس التصميم", Low: "منخفض", Medium: "متوسط", High: "مرتفع", Page: "صفحة", Score: "النتيجة", "One focused question": "سؤال واحد مركز", "Strong topic": "موضوع قوي", "Keep it warm": "حافظ على مستواه", "Next step": "الخطوة التالية", "Review mistakes": "راجع الأخطاء", Confidence: "الثقة", Easy: "سهل", Good: "جيد", "Need review": "يحتاج مراجعة",
  },
  es: { "30 minutes": "30 minutos", "6 days": "6 días", "2 tasks": "2 tareas", min: "min", days: "días", "min studied": "min estudiados", "weak topics": "temas débiles", Understand: "Comprender", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Convierte clases, notas, imágenes y audio en temas, explicaciones y resúmenes vinculados a fuentes.", Practice: "Practicar", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Obtén preguntas adaptadas a la materia, desde definiciones y cálculos hasta razonamiento abierto.", "Know what is next": "Saber qué sigue", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "El planificador considera exámenes, puntos débiles, confianza y tiempo para elegir la próxima sesión útil.", "Separate subject spaces": "Espacios separados por materia", "Save what matters": "Guarda lo importante", "Sessions that resume": "Sesiones que se reanudan", "Private by design": "Privacidad desde el diseño", Low: "Baja", Medium: "Media", High: "Alta", Page: "Página", Score: "Puntuación", "One focused question": "Una pregunta enfocada", "Strong topic": "Tema fuerte", "Keep it warm": "Mantén el nivel", "Next step": "Siguiente paso", "Review mistakes": "Revisa los errores", Confidence: "Confianza", Easy: "Fácil", Good: "Bien", "Need review": "Necesita repaso" },
  pt: { "30 minutes": "30 minutos", "6 days": "6 dias", "2 tasks": "2 tarefas", min: "min", days: "dias", "min studied": "min estudados", "weak topics": "tópicos fracos", Understand: "Entender", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Transforme aulas, notas, imagens e áudio em tópicos, explicações e resumos ligados às fontes.", Practice: "Praticar", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Receba perguntas adequadas à matéria, de definições e cálculos a raciocínio aberto.", "Know what is next": "Saiba o próximo passo", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "O planejador considera provas, pontos fracos, confiança e tempo para escolher a próxima sessão útil.", "Separate subject spaces": "Espaços separados por matéria", "Save what matters": "Salve o que importa", "Sessions that resume": "Sessões retomáveis", "Private by design": "Privacidade desde o design", Low: "Baixa", Medium: "Média", High: "Alta", Page: "Página", Score: "Pontuação", "One focused question": "Uma pergunta focada", "Strong topic": "Tópico forte", "Keep it warm": "Mantenha o nível", "Next step": "Próximo passo", "Review mistakes": "Revise os erros", Confidence: "Confiança", Easy: "Fácil", Good: "Bom", "Need review": "Precisa revisar" },
  fr: { "30 minutes": "30 minutes", "6 days": "6 jours", "2 tasks": "2 tâches", min: "min", days: "jours", "min studied": "min étudiées", "weak topics": "thèmes faibles", Understand: "Comprendre", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Transformez cours, notes, images et audio en thèmes, explications et résumés liés aux sources.", Practice: "Pratiquer", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Obtenez des questions adaptées à la matière, des définitions aux calculs et au raisonnement ouvert.", "Know what is next": "Savoir quoi faire ensuite", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "Le planificateur tient compte des examens, faiblesses, confiance et temps pour choisir la prochaine session utile.", "Separate subject spaces": "Espaces séparés par matière", "Save what matters": "Enregistrer l’essentiel", "Sessions that resume": "Sessions reprenables", "Private by design": "Confidentialité par conception", Low: "Faible", Medium: "Moyenne", High: "Élevée", Page: "Page", Score: "Score", "One focused question": "Une question ciblée", "Strong topic": "Thème solide", "Keep it warm": "Entretenez ce niveau", "Next step": "Prochaine étape", "Review mistakes": "Revoir les erreurs", Confidence: "Confiance", Easy: "Facile", Good: "Bien", "Need review": "À revoir" },
  de: { "30 minutes": "30 Minuten", "6 days": "6 Tage", "2 tasks": "2 Aufgaben", min: "Min.", days: "Tage", "min studied": "Min. gelernt", "weak topics": "schwache Themen", Understand: "Verstehen", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Verwandle Vorlesungen, Notizen, Bilder und Audio in Themen, Erklärungen und quellenbezogene Zusammenfassungen.", Practice: "Üben", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Erhalte passende Fragen, von Definitionen und Berechnungen bis zum offenen Denken.", "Know what is next": "Wissen, was als Nächstes kommt", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "Der Lernplaner berücksichtigt Prüfungen, Schwächen, Vertrauen und Zeit für die nächste sinnvolle Sitzung.", "Separate subject spaces": "Getrennte Fachbereiche", "Save what matters": "Wichtiges speichern", "Sessions that resume": "Fortsetzbare Sitzungen", "Private by design": "Datenschutz als Grundprinzip", Low: "Niedrig", Medium: "Mittel", High: "Hoch", Page: "Seite", Score: "Punktzahl", "One focused question": "Eine fokussierte Frage", "Strong topic": "Starkes Thema", "Keep it warm": "Auf dem Niveau bleiben", "Next step": "Nächster Schritt", "Review mistakes": "Fehler wiederholen", Confidence: "Sicherheit", Easy: "Einfach", Good: "Gut", "Need review": "Wiederholen" },
  it: { "30 minutes": "30 minuti", "6 days": "6 giorni", "2 tasks": "2 attività", min: "min", days: "giorni", "min studied": "min studiati", "weak topics": "argomenti deboli", Understand: "Capire", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Trasforma lezioni, note, immagini e audio in argomenti, spiegazioni e sintesi collegate alle fonti.", Practice: "Esercitarsi", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Ottieni domande adatte alla materia, da definizioni e calcoli al ragionamento aperto.", "Know what is next": "Sapere cosa viene dopo", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "Il pianificatore considera esami, punti deboli, fiducia e tempo per scegliere la prossima sessione utile.", "Separate subject spaces": "Spazi separati per materia", "Save what matters": "Salva ciò che conta", "Sessions that resume": "Sessioni riprendibili", "Private by design": "Privacy integrata nel design", Low: "Bassa", Medium: "Media", High: "Alta", Page: "Pagina", Score: "Punteggio", "One focused question": "Una domanda mirata", "Strong topic": "Argomento forte", "Keep it warm": "Mantieni il livello", "Next step": "Prossimo passo", "Review mistakes": "Rivedi gli errori", Confidence: "Sicurezza", Easy: "Facile", Good: "Bene", "Need review": "Da rivedere" },
  tr: { "30 minutes": "30 dakika", "6 days": "6 gün", "2 tasks": "2 görev", min: "dk", days: "gün", "min studied": "çalışılan dk", "weak topics": "zayıf konular", Understand: "Anla", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Dersleri, notları, görselleri ve sesi konulara, açıklamalara ve kaynak bağlantılı özetlere dönüştür.", Practice: "Pratik yap", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Tanımlardan hesaplamalara ve açık uçlu düşünmeye kadar derse uygun sorular al.", "Know what is next": "Sırada ne olduğunu bil", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "Çalışma planlayıcı sınavları, zayıf alanları, güveni ve zamanı değerlendirir.", "Separate subject spaces": "Ayrı ders alanları", "Save what matters": "Önemli olanı kaydet", "Sessions that resume": "Devam edilebilir oturumlar", "Private by design": "Tasarımın temeli gizlilik", Low: "Düşük", Medium: "Orta", High: "Yüksek", Page: "Sayfa", Score: "Puan", "One focused question": "Tek odaklı soru", "Strong topic": "Güçlü konu", "Keep it warm": "Seviyeyi koru", "Next step": "Sonraki adım", "Review mistakes": "Hataları gözden geçir", Confidence: "Güven", Easy: "Kolay", Good: "İyi", "Need review": "Tekrar gerekli" },
  ja: { "30 minutes": "30分", "6 days": "6日", "2 tasks": "2つのタスク", min: "分", days: "日", "min studied": "学習時間", "weak topics": "苦手なトピック", Understand: "理解", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "講義、ノート、画像、音声をトピック、解説、出典付き要約に変換します。", Practice: "練習", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "定義や計算から自由記述の推論まで、科目に合った問題を出します。", "Know what is next": "次にすることを知る", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "試験、苦手分野、自信、時間を考慮して次の学習を選びます。", "Separate subject spaces": "科目ごとのスペース", "Save what matters": "大切なものを保存", "Sessions that resume": "再開できるセッション", "Private by design": "プライバシー重視", Low: "低い", Medium: "中", High: "高い", Page: "ページ", Score: "スコア", "One focused question": "集中した1問", "Strong topic": "得意なトピック", "Keep it warm": "感覚を保つ", "Next step": "次のステップ", "Review mistakes": "間違いを復習", Confidence: "自信", Easy: "簡単", Good: "良い", "Need review": "要復習" },
  ko: { "30 minutes": "30분", "6 days": "6일", "2 tasks": "작업 2개", min: "분", days: "일", "min studied": "학습 시간", "weak topics": "취약한 주제", Understand: "이해", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "강의, 노트, 이미지와 오디오를 주제, 설명, 출처가 연결된 요약으로 바꿉니다.", Practice: "연습", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "정의와 계산부터 개방형 추론까지 과목에 맞는 문제를 받습니다.", "Know what is next": "다음 할 일 알기", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "시험, 취약점, 자신감과 시간을 고려해 다음 학습을 선택합니다.", "Separate subject spaces": "과목별 공간", "Save what matters": "중요한 내용 저장", "Sessions that resume": "재개 가능한 세션", "Private by design": "설계부터 개인정보 보호", Low: "낮음", Medium: "보통", High: "높음", Page: "페이지", Score: "점수", "One focused question": "집중 문제 하나", "Strong topic": "강한 주제", "Keep it warm": "감각 유지", "Next step": "다음 단계", "Review mistakes": "실수 복습", Confidence: "자신감", Easy: "쉬움", Good: "좋음", "Need review": "복습 필요" },
  zh: { "30 minutes": "30分钟", "6 days": "6天", "2 tasks": "2个任务", min: "分钟", days: "天", "min studied": "学习分钟", "weak topics": "薄弱主题", Understand: "理解", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "将讲座、笔记、图片和音频转成主题、解释和带来源的摘要。", Practice: "练习", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "获得适合这门课的问题，从定义和计算到开放式推理。", "Know what is next": "知道下一步", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "学习计划会结合考试、薄弱点、信心和时间选择下一次有效学习。", "Separate subject spaces": "独立的科目空间", "Save what matters": "保存重要内容", "Sessions that resume": "可继续的学习会话", "Private by design": "以隐私为设计基础", Low: "低", Medium: "中", High: "高", Page: "页", Score: "得分", "One focused question": "一道聚焦问题", "Strong topic": "擅长主题", "Keep it warm": "保持熟练", "Next step": "下一步", "Review mistakes": "复习错误", Confidence: "信心", Easy: "简单", Good: "不错", "Need review": "需要复习" },
  hi: { "30 minutes": "30 मिनट", "6 days": "6 दिन", "2 tasks": "2 कार्य", min: "मिनट", days: "दिन", "min studied": "पढ़े गए मिनट", "weak topics": "कमज़ोर विषय", Understand: "समझें", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "लेक्चर, नोट्स, चित्र और ऑडियो को विषयों, व्याख्याओं और स्रोत-लिंक वाले सारांश में बदलें।", Practice: "अभ्यास करें", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "परिभाषाओं और गणनाओं से लेकर खुले तर्क तक विषय के अनुरूप प्रश्न पाएं।", "Know what is next": "अगला कदम जानें", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "स्टडी मैनेजर परीक्षा, कमज़ोर क्षेत्रों, आत्मविश्वास और समय से अगला उपयोगी सत्र चुनता है।", "Separate subject spaces": "अलग विषय स्थान", "Save what matters": "ज़रूरी चीज़ें सहेजें", "Sessions that resume": "फिर शुरू होने वाले सत्र", "Private by design": "डिज़ाइन में गोपनीयता", Low: "कम", Medium: "मध्यम", High: "उच्च", Page: "पृष्ठ", Score: "स्कोर", "One focused question": "एक केंद्रित प्रश्न", "Strong topic": "मज़बूत विषय", "Keep it warm": "अभ्यास बनाए रखें", "Next step": "अगला कदम", "Review mistakes": "गलतियों की समीक्षा", Confidence: "आत्मविश्वास", Easy: "आसान", Good: "अच्छा", "Need review": "समीक्षा चाहिए" },
  ru: { "30 minutes": "30 минут", "6 days": "6 дней", "2 tasks": "2 задачи", min: "мин", days: "дней", "min studied": "мин. изучено", "weak topics": "слабые темы", Understand: "Понять", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Превращайте лекции, заметки, изображения и аудио в темы, объяснения и резюме с источниками.", Practice: "Практиковаться", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Получайте вопросы по предмету: от определений и расчётов до открытого рассуждения.", "Know what is next": "Знать следующий шаг", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "Планировщик учитывает экзамены, слабые места, уверенность и время.", "Separate subject spaces": "Отдельные пространства предметов", "Save what matters": "Сохранить важное", "Sessions that resume": "Возобновляемые сессии", "Private by design": "Конфиденциальность в основе", Low: "Низкая", Medium: "Средняя", High: "Высокая", Page: "Страница", Score: "Результат", "One focused question": "Один сфокусированный вопрос", "Strong topic": "Сильная тема", "Keep it warm": "Поддерживайте уровень", "Next step": "Следующий шаг", "Review mistakes": "Повторить ошибки", Confidence: "Уверенность", Easy: "Легко", Good: "Хорошо", "Need review": "Нужно повторить" },
  id: { "30 minutes": "30 menit", "6 days": "6 hari", "2 tasks": "2 tugas", min: "mnt", days: "hari", "min studied": "mnt belajar", "weak topics": "topik lemah", Understand: "Pahami", "Turn lectures, notes, images, and audio into topics, explanations, and source-linked summaries.": "Ubah kuliah, catatan, gambar, dan audio menjadi topik, penjelasan, dan ringkasan dengan sumber.", Practice: "Berlatih", "Get questions that fit the subject — from definitions to calculations and open-ended reasoning.": "Dapatkan pertanyaan sesuai pelajaran, dari definisi dan perhitungan hingga penalaran terbuka.", "Know what is next": "Tahu langkah berikutnya", "Study Manager weighs exams, weak areas, confidence, and time to choose the next useful session.": "Pengelola belajar mempertimbangkan ujian, kelemahan, keyakinan, dan waktu untuk memilih sesi berikutnya.", "Separate subject spaces": "Ruang terpisah tiap pelajaran", "Save what matters": "Simpan yang penting", "Sessions that resume": "Sesi yang dapat dilanjutkan", "Private by design": "Privasi sejak awal desain", Low: "Rendah", Medium: "Sedang", High: "Tinggi", Page: "Halaman", Score: "Nilai", "One focused question": "Satu pertanyaan fokus", "Strong topic": "Topik kuat", "Keep it warm": "Pertahankan kemampuan", "Next step": "Langkah berikutnya", "Review mistakes": "Tinjau kesalahan", Confidence: "Keyakinan", Easy: "Mudah", Good: "Bagus", "Need review": "Perlu ditinjau" },
};

export function setActiveLocale(locale: Locale) {
  activeLocale = locale;
}

export function getDictionary(locale: Locale) {
  return dictionary[locale] ?? dictionary.en;
}

export function trStatic(source: string, locale: Locale = activeLocale) {
  const catalog = dictionary[locale] as Record<string, string> | undefined;
  return supplementalTranslations[locale]?.[source] ?? catalog?.[source] ?? source;
}

export function getDirection(locale: Locale) {
  return supportedLocales.find((item) => item.code === locale)?.dir ?? "ltr";
}

export function formatExamText(date: string | undefined, locale: Locale = activeLocale) {
  if (!date) return trStatic("No exam date", locale);
  const days = Math.max(0, Math.ceil((new Date(date).getTime() - Date.now()) / 86400000));
  if (days === 0) return trStatic("Exam today", locale);
  return new Intl.RelativeTimeFormat(locale, { numeric: "always" }).format(days, "day");
}

export function formatNumber(value: number, locale: Locale = activeLocale) {
  return new Intl.NumberFormat(locale).format(value);
}
