import crypto from "node:crypto";
import { promisify } from "node:util";
import type { Express, Request, Response } from "express";
import { SignJWT, jwtVerify } from "jose";
import { eq } from "drizzle-orm";
import { parse as parseCookies } from "cookie";
import { users } from "../../drizzle/schema";
import { getDb } from "../db";
import { getSessionCookieOptions } from "./cookies";
import { COOKIE_NAME, ONE_YEAR_MS } from "@shared/const";

const scrypt = promisify(crypto.scrypt);
const providers = ["google", "apple", "microsoft"] as const;
type Provider = (typeof providers)[number];
type OAuthProfile = { id: string; email: string; name: string };
const providerEnv = (provider: Provider) => ({
  google: { clientId: process.env.GOOGLE_CLIENT_ID, clientSecret: process.env.GOOGLE_CLIENT_SECRET, authorize: "https://accounts.google.com/o/oauth2/v2/auth", token: "https://oauth2.googleapis.com/token", scope: "openid email profile" },
  microsoft: { clientId: process.env.MICROSOFT_CLIENT_ID, clientSecret: process.env.MICROSOFT_CLIENT_SECRET, authorize: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", token: "https://login.microsoftonline.com/common/oauth2/v2.0/token", scope: "openid email profile User.Read" },
  apple: { clientId: process.env.APPLE_CLIENT_ID, clientSecret: process.env.APPLE_CLIENT_SECRET, authorize: "https://appleid.apple.com/auth/authorize", token: "https://appleid.apple.com/auth/token", scope: "name email" },
}[provider]);

function secret() { const value = process.env.AUTH_SESSION_SECRET; if (!value || value.length < 32) throw new Error("AUTH_SESSION_SECRET must be at least 32 characters"); return new TextEncoder().encode(value); }
async function hashPassword(password: string) { const salt = crypto.randomBytes(16).toString("hex"); const derived = await scrypt(password, salt, 64) as Buffer; return `${salt}:${derived.toString("hex")}`; }
async function verifyPassword(password: string, stored: string) { const [salt, hash] = stored.split(":"); if (!salt || !hash) return false; const derived = await scrypt(password, salt, 64) as Buffer; return crypto.timingSafeEqual(Buffer.from(hash, "hex"), derived); }
async function sessionToken(userId: number) { return new SignJWT({ userId }).setProtectedHeader({ alg: "HS256" }).setIssuedAt().setExpirationTime("1y").sign(secret()); }
function requestCookies(req: Request) { return parseCookies(req.headers.cookie ?? ""); }
async function userFromRequest(req: Request) { const token = requestCookies(req)[COOKIE_NAME] ?? req.headers.authorization?.replace(/^Bearer /, ""); if (!token) return null; try { const { payload } = await jwtVerify(token, secret()); const db = await getDb(); if (!db || typeof payload.userId !== "number") return null; const rows = await db.select().from(users).where(eq(users.id, payload.userId)).limit(1); return rows[0] ?? null; } catch { return null; } }
async function signIn(res: Response, user: typeof users.$inferSelect) { res.cookie(COOKIE_NAME, await sessionToken(user.id), { ...getSessionCookieOptions({} as Request), maxAge: ONE_YEAR_MS }); }
async function findOrCreate(profile: OAuthProfile, provider: string) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select().from(users).where(eq(users.openId, `${provider}:${profile.id}`)).limit(1); if (existing[0]) return existing[0]; const byEmail = await db.select().from(users).where(eq(users.email, profile.email)).limit(1); if (byEmail[0]) return byEmail[0]; await db.insert(users).values({ openId: `${provider}:${profile.id}`, email: profile.email, name: profile.name, loginMethod: provider, lastSignedIn: new Date() }); const created = await db.select().from(users).where(eq(users.openId, `${provider}:${profile.id}`)).limit(1); return created[0]; }

async function exchange(provider: Provider, code: string, redirectUri: string): Promise<OAuthProfile> { const config = providerEnv(provider); if (!config.clientId || !config.clientSecret) throw new Error(`${provider.toUpperCase()} OAuth is not configured`); const body = new URLSearchParams({ code, client_id: config.clientId, client_secret: config.clientSecret, redirect_uri: redirectUri, grant_type: "authorization_code" }); if (provider === "apple") body.set("scope", "name email"); const tokenResponse = await fetch(config.token, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body }); if (!tokenResponse.ok) throw new Error(`OAuth token exchange failed for ${provider}`); const token = await tokenResponse.json() as { access_token?: string; id_token?: string }; if (provider === "apple") { const payload = JSON.parse(Buffer.from((token.id_token ?? "").split(".")[1] ?? "", "base64url").toString()) as { sub?: string; email?: string }; if (!payload.sub || !payload.email) throw new Error("Apple profile is incomplete"); return { id: payload.sub, email: payload.email, name: payload.email.split("@")[0] }; } const profileUrl = provider === "google" ? "https://openidconnect.googleapis.com/v1/userinfo" : "https://graph.microsoft.com/oidc/userinfo"; const profileResponse = await fetch(profileUrl, { headers: { authorization: `Bearer ${token.access_token}` } }); if (!profileResponse.ok) throw new Error(`Could not read ${provider} profile`); const profile = await profileResponse.json() as { sub?: string; id?: string; email?: string; preferred_username?: string; name?: string }; const email = profile.email ?? profile.preferred_username; const id = profile.sub ?? profile.id; if (!email || !id) throw new Error(`${provider} profile is incomplete`); return { id, email, name: profile.name ?? email.split("@")[0] }; }

export async function registerCustomAuthRoutes(app: Express) {
  app.get("/api/auth/:provider", (req, res) => { const rawProvider = req.params.provider; if (rawProvider === "email") { res.redirect("/login?mode=email"); return; } if (!providers.includes(rawProvider as Provider)) { res.status(404).send("Unsupported authentication provider"); return; } const provider = rawProvider as Provider; const config = providerEnv(provider); if (!config.clientId) { res.status(503).send(`${provider} authentication is not configured yet`); return; } const state = crypto.randomBytes(24).toString("hex"); res.cookie(`oauth_state_${provider}`, state, { ...getSessionCookieOptions(req), maxAge: 10 * 60 * 1000 }); const url = new URL(config.authorize); url.searchParams.set("client_id", config.clientId); url.searchParams.set("redirect_uri", `${req.protocol}://${req.get("host")}/api/auth/callback/${provider}`); url.searchParams.set("response_type", "code"); url.searchParams.set("scope", config.scope); url.searchParams.set("state", state); if (provider === "apple") url.searchParams.set("response_mode", "form_post"); res.redirect(url.toString()); });
  app.all("/api/auth/callback/:provider", async (req, res) => { const provider = req.params.provider as Provider; try { const state = String(req.body?.state ?? req.query.state ?? ""); const code = String(req.body?.code ?? req.query.code ?? ""); if (!providers.includes(provider) || !code || state !== requestCookies(req)[`oauth_state_${provider}`]) return res.status(400).send("Invalid authentication callback"); const profile = await exchange(provider, code, `${req.protocol}://${req.get("host")}/api/auth/callback/${provider}`); const user = await findOrCreate(profile, provider); if (!user) throw new Error("Could not create user"); await signIn(res, user); res.redirect("/"); } catch (error) { console.error("[Custom Auth] OAuth callback failed", error); res.status(500).send("Authentication could not be completed"); } });
  app.post("/api/auth/email", async (req, res) => { try { const { email, password, name, mode = "login" } = req.body as { email?: string; password?: string; name?: string; mode?: string }; const normalized = email?.trim().toLowerCase(); if (!normalized || !password || password.length < 8) return res.status(400).json({ error: "Email and a password of at least 8 characters are required" }); const db = await getDb(); if (!db) return res.status(503).json({ error: "Database is not available" }); const rows = await db.select().from(users).where(eq(users.email, normalized)).limit(1); let user = rows[0]; if (mode === "register") { if (user) return res.status(409).json({ error: "An account with this email already exists" }); await db.insert(users).values({ openId: `email:${crypto.randomUUID()}`, email: normalized, name: name?.trim() || normalized.split("@")[0], loginMethod: "email", passwordHash: await hashPassword(password), lastSignedIn: new Date() }); user = (await db.select().from(users).where(eq(users.email, normalized)).limit(1))[0]; } else { if (!user?.passwordHash || !(await verifyPassword(password, user.passwordHash))) return res.status(401).json({ error: "Invalid email or password" }); } if (!user) return res.status(500).json({ error: "Could not create account" }); await signIn(res, user); res.json({ success: true }); } catch (error) { console.error("[Custom Auth] Email auth failed", error); res.status(500).json({ error: "Email authentication failed" }); } });
  app.post("/api/auth/logout", (_req, res) => { res.clearCookie(COOKIE_NAME, getSessionCookieOptions(_req)); res.json({ success: true }); });
}
export { userFromRequest };
